### ISSUE TITLE
Add Missing Methods for Feeds

### ISSUE THREAD

**Issue by Cliftonz** [novuhq/novu-rust#17] opened 2023-10-02 23:02 UTC
Some endpoints of the following section can't be hit from this SDK. 

We would like to ensure that all endpoints can be hit. For this issue, we would like to build out the Feeds

Some of these methods may already exist.  If so no need to change/update them, just point out that they already exist and we will close the issue.  This is just to bring every SDK we have on par with all the methods available.

Check all the endpoints [here](https://api.novu.co/api#/Workflow%20groups/NotificationGroupsController_updateNotificationGroup) and add the missing ones.

**Comment by Aunali321** [comment] 2023-10-08 19:57
Hello, i'd like to work on this

**Comment by unicodeveloper** [comment] 2023-10-09 08:27
Assigning this to you now @Aunali321

**Comment by unicodeveloper** [comment] 2023-10-09 08:33
For more context: these are the endpoints/methods you are building out and you can test them out here by using your API Key.

- Get Feeds: https://docs.novu.co/api-reference/feeds/get-feeds
- Create Feed: https://docs.novu.co/api-reference/feeds/create-feed
- Delete Feed: https://docs.novu.co/api-reference/feeds/delete-feed

**Comment by Aunali321** [comment] 2023-10-09 08:48
> For more context: these are the endpoints/methods you are building out and you can test them out here by using your API Key.
> 
>     * Get Feeds: https://docs.novu.co/api-reference/feeds/get-feeds
> 
>     * Create Feed: https://docs.novu.co/api-reference/feeds/create-feed
> 
>     * Delete Feed: https://docs.novu.co/api-reference/feeds/delete-feed

I have already implemented some of the methods. how can i test them?

**Comment by unicodeveloper** [comment] 2023-10-09 08:57
I am not sure I get what you mean? Whenever you are building features, you test locally to be sure it works on your local rust environment, hits the API and returns the appropriate response. 

Don't you have your Rust environment set up?

**Comment by Aunali321** [comment] 2023-10-09 08:59
I mean something like a mock server

**Comment by unicodeveloper** [comment] 2023-10-09 09:02
Your features should hit the real Novu API for you to be sure it's working as intended.

It's only when you are writing tests that you need a mock so you are not hitting the real API.

**Closed** 2023-10-12 03:37 UTC
Labels: hacktoberfest
